### PR TITLE
Added synthetic unit-tests

### PR DESCRIPTION
**Pull request by preseverence**
I added synthetic unit test.
As the app has no API, I called it from CLI as separate process and check the results.

### CODE REVIEW

**Comment by ZimM-LostPolygon** [comment]
Thank you for your contribution.

Since you've downgraded to 4.6.1, please add `System.ValueTuple` to the ILRepack call at the end of `AssemblyNamespaceChanger.csproj`. Otherwise LGTM!

**Comment by preseverence** [comment]
Try this one.

**Comment by ZimM-LostPolygon** [comment]
Thanks!

**Comment by preseverence** [comment]
Аффтар жжотъ.

**Pull request merged**
